import fs from "fs";
import path from "path";

export type TaskPriority = "low" | "medium" | "high" | "urgent";
export type TaskStatus = "pending" | "in_progress" | "completed" | "cancelled";
export type TaskRecurring = "none" | "daily" | "weekly" | "monthly";

export interface TaskItem {
  id: string;
  title: string;
  description?: string;
  category: string;
  priority: TaskPriority;
  status: TaskStatus;
  dueDate?: string;
  reminderTime?: string;
  recurring: TaskRecurring;
  createdAt: string;
  completedAt?: string;
}

const DATA_DIR = path.join(process.cwd(), "server", "data");
const TASKS_FILE = path.join(DATA_DIR, "tasks.json");

const defaultTasks: TaskItem[] = [
  {
    id: "task_1",
    title: "Review Aitzaz's CV & Portfolio",
    description: "Verify job readiness, skills alignment, and MICK OS highlight section.",
    category: "Career",
    priority: "high",
    status: "pending",
    dueDate: new Date(Date.now() + 86400000).toISOString().split("T")[0],
    recurring: "none",
    createdAt: new Date().toISOString(),
  },
  {
    id: "task_2",
    title: "Connect Google Workspace & OAuth",
    description: "Grant Gmail and Google Drive read scopes to MICK Email Agent.",
    category: "System",
    priority: "urgent",
    status: "pending",
    dueDate: new Date().toISOString().split("T")[0],
    recurring: "none",
    createdAt: new Date().toISOString(),
  },
  {
    id: "task_3",
    title: "Apply for Senior AI Engineer Positions",
    description: "Submit tailored cover letters generated by MICK Job Assistant.",
    category: "Job Hunt",
    priority: "high",
    status: "in_progress",
    dueDate: new Date(Date.now() + 172800000).toISOString().split("T")[0],
    recurring: "weekly",
    createdAt: new Date().toISOString(),
  }
];

class TaskEngine {
  private tasks: TaskItem[];

  constructor() {
    this.tasks = this.loadFromFile();
  }

  private ensureDir() {
    if (!fs.existsSync(DATA_DIR)) {
      fs.mkdirSync(DATA_DIR, { recursive: true });
    }
  }

  private loadFromFile(): TaskItem[] {
    try {
      this.ensureDir();
      if (fs.existsSync(TASKS_FILE)) {
        const raw = fs.readFileSync(TASKS_FILE, "utf-8");
        return JSON.parse(raw);
      }
    } catch (e) {
      console.error("Failed to load tasks file, using defaults", e);
    }
    return defaultTasks;
  }

  private saveToFile() {
    try {
      this.ensureDir();
      fs.writeFileSync(TASKS_FILE, JSON.stringify(this.tasks, null, 2), "utf-8");
    } catch (e) {
      console.error("Failed to write tasks file", e);
    }
  }

  public getTasks(filterStatus?: TaskStatus): TaskItem[] {
    if (filterStatus) {
      return this.tasks.filter((t) => t.status === filterStatus);
    }
    return this.tasks;
  }

  public createTask(data: {
    title: string;
    description?: string;
    category?: string;
    priority?: TaskPriority;
    dueDate?: string;
    reminderTime?: string;
    recurring?: TaskRecurring;
  }): TaskItem {
    const newTask: TaskItem = {
      id: `task_${Date.now()}_${Math.random().toString(36).substr(2, 4)}`,
      title: data.title,
      description: data.description || "",
      category: data.category || "General",
      priority: data.priority || "medium",
      status: "pending",
      dueDate: data.dueDate,
      reminderTime: data.reminderTime,
      recurring: data.recurring || "none",
      createdAt: new Date().toISOString(),
    };
    this.tasks.unshift(newTask);
    this.saveToFile();
    return newTask;
  }

  public updateTask(id: string, updates: Partial<TaskItem>): TaskItem | null {
    const index = this.tasks.findIndex((t) => t.id === id);
    if (index === -1) return null;

    if (updates.status === "completed" && this.tasks[index].status !== "completed") {
      updates.completedAt = new Date().toISOString();
    }

    this.tasks[index] = { ...this.tasks[index], ...updates };
    this.saveToFile();
    return this.tasks[index];
  }

  public completeTask(idOrTitle: string): TaskItem | null {
    const task = this.tasks.find(
      (t) => t.id === idOrTitle || t.title.toLowerCase().includes(idOrTitle.toLowerCase())
    );
    if (!task) return null;

    task.status = "completed";
    task.completedAt = new Date().toISOString();
    this.saveToFile();
    return task;
  }

  public cancelTask(idOrTitle: string): TaskItem | null {
    const task = this.tasks.find(
      (t) => t.id === idOrTitle || t.title.toLowerCase().includes(idOrTitle.toLowerCase())
    );
    if (!task) return null;

    task.status = "cancelled";
    this.saveToFile();
    return task;
  }

  public deleteTask(id: string): boolean {
    const prevLen = this.tasks.length;
    this.tasks = this.tasks.filter((t) => t.id !== id);
    if (this.tasks.length !== prevLen) {
      this.saveToFile();
      return true;
    }
    return false;
  }
}

export const taskEngine = new TaskEngine();
